<?php
/**
 * Created by PhpStorm.
 * User: asmo
 * Date: 16.08.18
 * Time: 12:12
 */

namespace frontend\models;


use yii\db\ActiveRecord;

class Fuel92 extends ActiveRecord
{
    public static function tableName()
    {
        return 'fuel92'; // TODO: Change the autogenerated stub
    }
}